# Generated by Django 2.1.7 on 2019-03-11 01:55

from decimal import Decimal
from django.db import migrations, models
import gallery.models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default=' ', max_length=100)),
                ('charge_info', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ClothingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('Nike', 'Nike'), ('Nautica', 'Nautica'), ('Calvin Klein', 'Calvin Klein'), ('Adidas', 'Adidas'), ('Columbia', 'Columbia')], max_length=100)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('image', models.ImageField(default=None, upload_to=gallery.models._photo_upload)),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
